### ISSUE TITLE
希望前端部分能够开源

### ISSUE THREAD

**Issue by kekee000** [X-Profiler/xprofiler-console#11]
easy-monitor 这个项目真的很好，我们跑了上百个实例了，很稳定。
有一些定制化的开发需求，因为前端部分没开源，一直没办法做，
希望能够启动前端开源计划，感谢。

加油，加油。

**Comment by kekee000** [comment]
再次感谢^^

**Comment by binlaniua** [comment]
期待

**Comment by ZantiarvajGit** [comment]
ZantiarvajX-Profiler

**Comment by ZantiarvajGit** [comment]
Rjehe

**Comment by coder-layne** [comment]
@hyj1991 想问下进度如何了？🙏

**Comment by hyj1991** [comment]
> @hyj1991 想问下进度如何了？🙏

出于一些考虑，目前还没有计划

**Comment by coder-layne** [comment]
> > @hyj1991 想问下进度如何了？🙏
> 
> 出于一些考虑，目前还没有计划

感谢回复

**Comment by rushmc** [comment]
同上  希望前端部分能够开源，或者能够加入开发 回馈xprofiler项目组
