### ISSUE TITLE
[Feat] 内存趋势增加 external_memory 展示

### ISSUE THREAD

**Issue by hyj1991** [X-Profiler/xprofiler-console#16]

**Comment by fengmk2** [comment]
node 默认有给出这个接口？还是通过 v8 获取到的？

**Comment by hyj1991** [comment]
> node 默认有给出这个接口？还是通过 v8 获取到的？

新版本有 api，插件里直接读取的 v8 数据

**Comment by hyj1991** [comment]
已实现：54a7f5ea8435682a030626eff37122090baf4857
