### ISSUE TITLE
[RFC] 监控服务端项目部署模式增强

### ISSUE THREAD

**Issue by hyj1991** [X-Profiler/xprofiler-console#28]
## 背景

目前的部署模式下就算不做任何更改，依旧需要 clone 仓库代码进行发布，如果定制了一些内容后，对后续的合并上游更新会存在一定的困扰。

期望能够以 Npm 模块的方式进行发布和版本更新，引入项目后借助于 egg framework 的申明来直接继承使用。

Egg 3 中会原生对这种能力进行支持，目前计划通过原型链以 patch 的形式给 Egg 2.x 也实现相同的能力，方便私有化部署。

**Comment by hyj1991** [comment]
cc @fengmk2 @atian25

**Comment by fengmk2** [comment]
+1

**Comment by hyj1991** [comment]
已完成：https://github.com/X-Profiler/xprofiler-console/issues/31
