### ISSUE TITLE
项目部署在“域名/子目录”下，导致接口404

### ISSUE THREAD

**Issue by lx544690189** [X-Profiler/xprofiler-console#3]
前端项目没有开源吗？api应该请求的更路径，我想自己编译下。
建议：
/app/view/index.html中可以设置个全局变量window.__baseUrl，然后前端项目根据这个来设置接口更路径，这样灵活些。

**Comment by lx544690189** [comment]
界面写的很漂亮，如果前端项目开源就更好了😜

**Comment by hyj1991** [comment]
> 前端项目没有开源吗？api应该请求的更路径，我想自己编译下。
> 建议：
> /app/view/index.html中可以设置个全局变量window.__baseUrl，然后前端项目根据这个来设置接口更路径，这样灵活些。

这是个单独的项目，目前不支持也不建议配置虚拟路径转发，后面的话前端项目会视情况开源
