### ISSUE TITLE
支持企业微信webhook

### ISSUE THREAD

**Issue by kekee000** [X-Profiler/xprofiler-console#7]
hi，你好，我们在使用ezm搭建Node相关监控，想支持告警通知到企业微信，这块能支持一下么，多谢。
我们写了一个微信 webhook 到 xtransit-manager，不过 xprofiler-console 前端没开源，加不了。

**Comment by hyj1991** [comment]
可以，我处理下这个

**Comment by hyj1991** [comment]
企业微信的 webhook 接入有文档么

**Comment by kekee000** [comment]
企业微信 POST 发送指定内容到 webhooks上，只有url，不需要签名

例如发送 text文本类型，支持@人和手机号:

```
curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${key}' \
   -H 'Content-Type: application/json' \
   -d '
   {
    "msgtype": "text",
    "text": {
        "content": "广州今日天气：29度，大部分多云，降雨概率：60%",
        "mentioned_list":["wangqing","@all"],
        "mentioned_mobile_list":["13800001111","@all"]
    }
}'

```

参数说明：

| 参数 |	是否必填 | 	说明 |
| :----: | :----: | :----: |
|msgtype |是	|消息类型，此时固定为text|
|content |是	|文本内容，最长不超过2048个字节，必须是utf8编码|
|mentioned_list	|否	|userid的列表，提醒群中的指定成员(@某个成员)，<br>@all表示提醒所有人，如果开发者获取不到userid，可以使用mentioned_mobile_list|
|mentioned_mobile_list|	否|	手机号列表，提醒手机号对应的群成员(@某个成员)，@all表示提醒所有人|



我们需要发送 Markdown格式文本，支持服务号群发:

```json
{
    "msgtype": "markdown",
    "markdown": {
        "content": "实时新增用户反馈<font color=\"warning\">132例</font>，请相关同事注意。\n
         >类型:<font color=\"comment\">用户反馈</font>
         >普通用户反馈:<font color=\"comment\">117例</font>
         >VIP用户反馈:<font color=\"comment\">15例</font>"
    }
}
```

**Comment by hyj1991** [comment]
> 企业微信 POST 发送指定内容到 webhooks上，只有url，不需要签名
> 
> 例如发送 text文本类型，支持@人和手机号:
> 
> ```
> curl 'https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=${key}' \
>    -H 'Content-Type: application/json' \
>    -d '
>    {
>     "msgtype": "text",
>     "text": {
>         "content": "广州今日天气：29度，大部分多云，降雨概率：60%",
>         "mentioned_list":["wangqing","@all"],
>         "mentioned_mobile_list":["13800001111","@all"]
>     }
> }'
> ```
> 
> 参数说明：
> 
> 参数	是否必填	说明
> msgtype	是	消息类型，此时固定为text
> content	是	文本内容，最长不超过2048个字节，必须是utf8编码
> mentioned_list	否	userid的列表，提醒群中的指定成员(@某个成员)，
> @ALL表示提醒所有人，如果开发者获取不到userid，可以使用mentioned_mobile_list
> mentioned_mobile_list	否	手机号列表，提醒手机号对应的群成员(@某个成员)，@ALL表示提醒所有人
> 我们需要发送 Markdown格式文本，支持服务号群发:
> 
> ```json
> {
>     "msgtype": "markdown",
>     "markdown": {
>         "content": "实时新增用户反馈<font color=\"warning\">132例</font>，请相关同事注意。\n
>          >类型:<font color=\"comment\">用户反馈</font>
>          >普通用户反馈:<font color=\"comment\">117例</font>
>          >VIP用户反馈:<font color=\"comment\">15例</font>"
>     }
> }
> ```

这个看起来比钉钉机器人简单，我周末加下，回头需要你测试验证下，你可以加钉钉群方便沟通。

**Comment by hyj1991** [comment]
已经支持企业微信推送了，可以测试下。

更新方法：
* 更新 [xprofiler-console](https://github.com/X-Profiler/xprofiler-console) 代码到最新的 master 分支代码
* 更新 [xtransit-manager](https://github.com/X-Profiler/xtransit-manager) 代码到最新 master 分支代码
* 重新启动上述两个应用即可

效果截图：

![image](https://user-images.githubusercontent.com/19908330/87237650-91faec00-c42b-11ea-82b6-1ed7d089fcae.png)

相关的 Commit：

* https://github.com/X-Profiler/xprofiler-console/commit/5e9151eec0983fd34df8b6e9d3a1cbea319b35ff
* https://github.com/X-Profiler/xtransit-manager/commit/0b5cc62648b332a32daf5980a4d9c8883328580b

**Comment by hyj1991** [comment]
如果测试有问题可以在这里反馈

**Comment by kekee000** [comment]
试用了没问题，感谢支持
