### ISSUE TITLE
xprofilerConsole address should be placed in xtransit config

### ISSUE THREAD

**Issue by AvailCat** [X-Profiler/xprofiler-console#9]
**Problem**: Server address used to upload dump file was specified by server, this prevent clients in isolated network to upload file.
**Network map**:
 - X-Profiler Server (3 services): Internet access with IP 123.x.x.x, private network access with IP 10.x.x.x
 - X-Profiler and x-transit client A: Internet access with IP 123.x.x.x, no private network access.
 - X-Profiler and x-transit client B: No internet access, private network access with IP 10.x.x.x

By read source code, i can see the address used to upload was specified in command data, and this address was hard coded in server side config file, this cause one of above client not able to upload file.

Other function works well because socket server address was specified in client config file, so i think this address should also specify in client config.

**Comment by hyj1991** [comment]
This is because when the upload server changes we needn't update client config. In fact, deploy separately or make a proxy is better in this situation.
